import { app } from '../firebase-config.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/10.8.0/firebase-functions.js';
import { lobbyCapacity, roomCountPayload } from './online-compat.js';

const auth = getAuth(app); const functions = getFunctions(app, 'asia-northeast1');
const el = (id) => document.getElementById(id); const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const desiredCount = Math.min(4, Math.max(2, Number(new URLSearchParams(location.search).get('players')) || 2));
const ORES = { iron: { name: '鉄晶', icon: '◇', value: 1, danger: '低' }, azure: { name: '蒼晶', icon: '◆', value: 2, danger: '中' }, gold: { name: '金晶', icon: '✦', value: 3, danger: '高' } };
const ACTIONS = { mine: ['⛏️', '採掘', '公開で2個'], reinforce: ['🛠️', '補強', '危険度−12'], secret: ['🤫', '隠匿採掘', '1公開＋1秘密'], retreat: ['🚪', '撤退', '利益を確定'] };
const state = { roomId: localStorage.getItem('deepMiningAgreementRoomId'), inviteCode: sessionStorage.getItem('deepMiningAgreementInviteCode'), snapshot: null, selected: null, selectedScout: false, selectedAccusation: null, busy: false };
const call = (name, data) => httpsCallable(functions, name)(data).then((response) => response.data);
const requestId = () => crypto.randomUUID().replaceAll('-', '_');
const message = (error) => error?.message?.replace(/^FirebaseError:\s*/, '') || '処理に失敗しました。';
function status(text) { el('status').textContent = text; }
function show(id) { ['entry', 'lobby', 'game'].forEach((name) => { el(name).hidden = name !== id; }); el('leave').hidden = id === 'entry'; }
function bagCount(bag) { return Object.values(bag || {}).reduce((sum, count) => sum + count, 0); }
function actionName(id) { return ACTIONS[id] ? `${ACTIONS[id][0]} ${ACTIONS[id][1]}` : '—'; }
function renderLobby(snapshot) { show('lobby'); el('shown-code').textContent = state.inviteCode || '参加済み'; el('copy-code').hidden = !state.inviteCode; el('members').innerHTML = snapshot.members.map((member) => `<li>${escapeHtml(member.displayName)}${member.seatId === snapshot.self.seatId ? '（あなた）' : ''}</li>`).join(''); const humanPlayerCount = lobbyCapacity(snapshot.room); const ready = snapshot.members.length === humanPlayerCount; const npcCount = 4 - humanPlayerCount; const readyNote = npcCount ? `全員揃いました。開始時にNPC${npcCount}人を加え、4席で遊びます。` : '全員揃いました。人間4人の4席で遊びます。'; el('lobby-note').textContent = `${snapshot.members.length} / ${humanPlayerCount}人参加中。${ready ? readyNote : '参加者を待っています。'}`; el('start-game').hidden = !snapshot.self.isHost; el('start-game').disabled = !ready; }
function renderHistory(game) { el('history').innerHTML = game.history.length ? [...game.history].reverse().map((record) => `<div class="history-item"><strong>第${record.round}R ${ORES[record.oreId].name}</strong><br>${game.players.map((p) => `${escapeHtml(p.name)}：${actionName(record.publicActions[p.id])}`).join('／')}<br>危険度 ${record.dangerBefore} → ${record.dangerAfter}、隠匿採掘 ${record.secretCount}件</div>`).join('') : '<p class="muted">まだ結果はありません。</p>'; }
function renderGame(snapshot) {
  show('game'); const game = snapshot.game; const mine = ORES[game.currentOreId]; const me = game.players.find((p) => p.id === snapshot.self.seatId); const submitted = game.submittedSeatIds.includes(snapshot.self.seatId);
  el('round').textContent = game.ended ? '採掘終了' : `第${game.round} / 8ラウンド`; el('you').textContent = `あなた：${snapshot.self.displayName}`; el('danger').textContent = `${game.danger}`; el('danger-fill').style.width = `${Math.min(100, game.danger)}%`; el('ore-icon').textContent = mine?.icon || '✓'; el('ore-name').textContent = mine?.name || '精算完了'; el('ore-note').textContent = mine ? `価値 ${mine.value}　危険 ${mine.danger}` : '';
  el('players').innerHTML = game.players.map((player) => `<article class="seat ${game.submittedSeatIds.includes(player.id) ? 'submitted' : ''}"><div class="seat-head"><strong>${escapeHtml(player.name)}${player.id === snapshot.self.seatId ? '（あなた）' : !player.isHuman ? '（NPC）' : ''}</strong><span class="badge">${player.active ? (game.submittedSeatIds.includes(player.id) ? '確定済み' : '在坑') : '撤退'}</span></div>${player.role ? `<p>${escapeHtml(player.role)}</p>` : ''}<p>公開所持 ${bagCount(player.publicOre)}個</p><p>補強貢献 ${player.reinforcement}</p></article>`).join('');
  el('action-panel').hidden = game.ended || !me?.active; el('wait-note').textContent = submitted ? '行動は確定済みです。他の参加者を待っています。' : '全員が確定すると同時に公開・解決します。';
  const enabled = { mine: true, reinforce: true, secret: game.round >= 3, retreat: game.round >= 5 }; el('actions').innerHTML = Object.entries(ACTIONS).map(([id, [icon, label, note]]) => `<button class="action-button" data-action-id="${id}" aria-pressed="${state.selected === id}" ${enabled[id] && !submitted ? '' : 'disabled'}><span class="action-icon">${icon}</span><span class="action-copy">${label}<small>${enabled[id] ? note : id === 'secret' ? '第3Rから' : '第5Rから'}</small></span></button>`).join('');
  el('scout').disabled = submitted || game.round >= 8 || game.selfPrivate.scoutsUsed >= 2; el('scout').checked = state.selectedScout; const canAccuse = game.round >= 3 && game.detectedSecretMining && game.selfPrivate.accusationsUsed < 2; el('accusation-wrap').hidden = !canAccuse || submitted; el('accusation').innerHTML = '<option value="">使わない</option>' + game.players.filter((p) => p.active && p.id !== snapshot.self.seatId).map((p) => `<option value="${p.id}" ${state.selectedAccusation === p.id ? 'selected' : ''}>${escapeHtml(p.name)}を告発</option>`).join(''); el('submit-action').disabled = submitted || !state.selected || state.busy;
  if (game.selfPrivate.scoutedOre) status(`偵察情報：今回の鉱脈は${ORES[game.selfPrivate.scoutedOre].name}です。`); else status(submitted ? '他の参加者の確定を待っています…' : 'あなたの行動を選んでください。'); renderHistory(game);
  el('result').hidden = !game.ended; if (game.ended) { const ordered = [...game.players].sort((a, b) => a.rank - b.rank); el('result').innerHTML = `<h2>採掘結果</h2><p>${game.endReason === 'collapse' ? '坑道が崩落しました。' : game.endReason === 'all-retreated' ? '全員が撤退しました。' : '8ラウンドが終了しました。'}</p><table class="final-table"><thead><tr><th>順位</th><th>採掘者</th><th>最終価値</th></tr></thead><tbody>${ordered.map((p) => `<tr><td>${p.rank}位</td><td>${escapeHtml(p.name)}</td><td>${p.finalValue}</td></tr>`).join('')}</tbody></table><p class="muted">秘密鉱石は終了時に公開されます。</p>`; status('ゲームが終了しました。'); }
}
async function refresh() { if (!state.roomId) return; try { const snapshot = await call('deepMiningAgreementGetSnapshot', { roomId: state.roomId }); state.snapshot = snapshot; if (snapshot.room.status === 'lobby') renderLobby(snapshot); else renderGame(snapshot); } catch (error) { status(message(error)); if (/参加していません|見つかりません/.test(message(error))) { localStorage.removeItem('deepMiningAgreementRoomId'); state.roomId = null; show('entry'); } } }
async function mutate(name, payload) { if (state.busy) return null; state.busy = true; status('処理中…'); try { return await call(name, { ...payload, requestId: requestId() }); } finally { state.busy = false; } }
el('mode-label').textContent = desiredCount < 4 ? `人間${desiredCount}人＋NPC${4 - desiredCount}人（4席対戦）` : '人間4人（4席対戦）';
el('create-room').onclick = async () => { try { const result = await mutate('deepMiningAgreementCreateRoom', { displayName: el('display-name').value, ...roomCountPayload(desiredCount) }); state.roomId = result.roomId; state.inviteCode = result.inviteCode; localStorage.setItem('deepMiningAgreementRoomId', state.roomId); sessionStorage.setItem('deepMiningAgreementInviteCode', state.inviteCode); await refresh(); } catch (error) { status(message(error)); } };
el('join-room').onclick = async () => { try { const result = await mutate('deepMiningAgreementJoinRoom', { displayName: el('display-name').value, inviteCode: el('invite-code').value }); state.roomId = result.roomId; state.inviteCode = null; localStorage.setItem('deepMiningAgreementRoomId', state.roomId); await refresh(); } catch (error) { status(message(error)); } };
el('copy-code').onclick = async () => { await navigator.clipboard.writeText(state.inviteCode); status('部屋コードをコピーしました。'); };
el('start-game').onclick = async () => { try { await mutate('deepMiningAgreementStartGame', { roomId: state.roomId, stateVersion: state.snapshot.room.stateVersion }); await refresh(); } catch (error) { status(message(error)); } };
el('actions').onclick = (event) => { const button = event.target.closest('[data-action-id]'); if (!button || button.disabled) return; state.selected = button.dataset.actionId; renderGame(state.snapshot); };
el('scout').onchange = () => { state.selectedScout = el('scout').checked; };
el('accusation').onchange = () => { state.selectedAccusation = el('accusation').value || null; };
el('submit-action').onclick = async () => { if (!state.selected) return; const game = state.snapshot.game; const selected = state.selected; try { el('submit-action').disabled = true; await mutate('deepMiningAgreementSubmitAction', { roomId: state.roomId, gameId: game.gameId, round: game.round, stateVersion: state.snapshot.room.stateVersion, action: selected, scout: state.selectedScout, accusationTarget: state.selectedAccusation }); state.selected = null; state.selectedScout = false; state.selectedAccusation = null; await refresh(); } catch (error) { status(message(error)); } };
el('leave').onclick = () => { localStorage.removeItem('deepMiningAgreementRoomId'); sessionStorage.removeItem('deepMiningAgreementInviteCode'); location.assign('./'); };

async function boot() { try { await auth.authStateReady(); if (!auth.currentUser) await signInAnonymously(auth); el('entry').hidden = false; status('オンライン対戦の準備ができました。'); if (state.roomId) await refresh(); setInterval(() => { if (state.roomId && !state.busy) refresh(); }, 2000); } catch (error) { status(message(error)); el('entry').hidden = false; } }
boot();
