import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { inspectReadiness, main, validateEmbedded, PINNED_HASHES, SOURCE_COMMIT } from '../scripts/inspect-floating-garden-readiness.mjs';
function fixture(options = {}) {
  const calls = [], lines = [];
  const modules = {
    apis: { async bootstrapApis(args) { calls.push(['apis', args.apply]); assert.equal(args.apply, false); if (options.fail === 'apis') throw Error('synthetic-secret'); return { complete: !options.missingApi, remaining: options.missingApi ? ['run.googleapis.com'] : [], buildAccount: '120030709276-compute@developer.gserviceaccount.com', bindings: [{ role: 'roles/editor', condition: null }] }; } },
    runtime: { async bootstrapRuntime(args) { calls.push(['runtime', args.apply]); assert.equal(args.apply, false); if (options.fail === 'runtime') throw Error('synthetic-secret'); return { complete: true, account: true, role: true, bound: true }; } },
    hmac: {
      validateEnvironment() { calls.push(['environment']); if (options.fail === 'environment') throw Error('synthetic-secret'); },
      async bootstrapHmac(args) { calls.push(['hmac', args.userOperated]); assert.equal(args.userOperated, false); if (options.fail === 'hmac') throw Error('synthetic-secret'); args.log('SECRET_ALREADY_EXISTS: synthetic-secret'); args.log('EXISTING_VERSION_STATES: ENABLED'); args.log('DIRECT_RUNTIME_ACCESSOR: present'); return { existing: !options.noSecret, created: false }; },
    },
  };
  const read = (args, format) => { calls.push(['read', args, format]); const command=args.slice(0,3).join(' '); assert.ok(['secrets versions list','secrets versions describe','run services list','artifacts repositories list'].includes(command)); assert.doesNotMatch(args.join(' '), /--quiet|print-access-token|versions access|enable|create|update|delete|deploy|add-iam|login/); if(options.fail===command)throw Error('synthetic-secret'); return []; };
  return { calls, lines, deps: { load: async () => modules, read, log: (line) => lines.push(line), env: {}, execArgv: [] } };
}
test('embedded dependency hashes exactly match the unchanged reviewed source',async()=>{validateEmbedded();assert.equal(SOURCE_COMMIT,'c932fbcaf2d83a124ebcf670b037f0edf5c336bf');assert.ok(Object.isFrozen(PINNED_HASHES));for(const name of ['apis','runtime','hmac'])assert.equal(createHash('sha256').update(await readFile(new URL(`../scripts/bootstrap-floating-garden-${name}.mjs`,import.meta.url))).digest('hex'),PINNED_HASHES[name]);});
test('plan and unknown/apply arguments never load dependencies',async()=>{for(const args of [[],['--plan']])assert.equal(await main(args,{log(){},load:()=>assert.fail('inert')}),0);for(const args of [['--apply'],['--inspect','--project=other'],['--inspect','--apply'],['--stop'],['--inspect=true']])assert.equal(await main(args,{log(){},load:()=>assert.fail('no load')}),1);});
test('only explicit read branches and four exact metadata calls run',async()=>{const f=fixture();assert.deepEqual(await inspectReadiness(f.deps),{snapshotComplete:true});assert.deepEqual(f.calls.slice(0,4),[['environment'],['apis',false],['runtime',false],['hmac',false]]);assert.equal(f.calls.filter(c=>c[0]==='read').length,4);assert.deepEqual(f.calls[4],['read',['secrets','versions','list','FLOATING_GARDEN_INVITE_HMAC_KEY'],'json(name,state)']);assert.deepEqual(f.calls[5],['read',['secrets','versions','describe','latest','--secret=FLOATING_GARDEN_INVITE_HMAC_KEY'],'json(name,state,replicationStatus)']);assert.match(f.lines.at(-1),/^SNAPSHOT_ONLY:.*missing fields are unknown/);assert.ok(!f.lines.join('\n').includes('synthetic-secret'));});
test('missing APIs stop before extra services, without enablement fallback',async()=>{const f=fixture({missingApi:true});assert.deepEqual(await inspectReadiness(f.deps),{snapshotComplete:false,stage:'apis'});assert.deepEqual(f.calls,[['environment'],['apis',false]]);});
test('absent HMAC is reported without version calls or generation',async()=>{const f=fixture({noSecret:true});assert.deepEqual(await inspectReadiness(f.deps),{snapshotComplete:true});assert.equal(f.calls.filter(c=>c[0]==='read').length,2);assert.ok(f.lines.includes('HMAC_EXISTS: false'));});
test('failed reads stop once with fixed labels and never echo raw exceptions',async()=>{for(const [fail,stage] of [['environment','local-source'],['apis','apis'],['runtime','runtime'],['hmac','hmac-metadata'],['secrets versions list','hmac-version-metadata'],['secrets versions describe','hmac-version-metadata'],['run services list','existing-run-services'],['artifacts repositories list','artifact-cleanup-metadata']]){const f=fixture({fail});assert.deepEqual(await inspectReadiness(f.deps),{snapshotComplete:false,stage});assert.ok(f.lines.at(-1).startsWith(`READ_STOP: ${stage}.`));assert.ok(!f.lines.join('\n').includes('synthetic-secret'));}});
test('main returns actual snapshot outcome and never retries',async()=>{for(const missingApi of [false,true]){const f=fixture({missingApi});assert.equal(await main(['--inspect'],f.deps),missingApi?1:0);assert.equal(f.calls.filter(c=>c[0]==='apis').length,1);}});
test('metadata runner pins project/quota, closes stdin and disables diagnostic logs',async()=>{const s=await readFile(new URL('../scripts/inspect-floating-garden-readiness.mjs',import.meta.url),'utf8');const r=s.slice(s.indexOf('export function readMetadata'),s.indexOf('// Injection is solely'));assert.match(r,/`--project=\$\{PROJECT\}`/);assert.match(r,/`--billing-project=\$\{PROJECT\}`/);assert.match(r,/stdio: \['ignore', 'pipe', 'pipe'\]/);assert.match(r,/CLOUDSDK_CORE_DISABLE_PROMPTS: 'false'/);assert.match(r,/CLOUDSDK_CORE_LOG_HTTP: 'false'/);assert.match(r,/CLOUDSDK_CORE_DISABLE_FILE_LOGGING: 'true'/);});
